# Generated by Django 4.0.6 on 2022-07-24 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='memo',
        ),
    ]
