---
title: "R による多変量解析入門データ分析の実践と理論 １章"
editor: source
date: "`r format(Sys.time(), '%Y/%m/%d')`"
toc: true
number-sections: true
format: 
  html:
    embed-resources: true
editor_options: 
  chunk_output_type: console
# jupyter: python3
---
```{r}
library(readr)

# CSVファイルを読み込み
jhk <- read_delim("R_MultivariateAnalysis/R_Multivariate Analysis0726/第01章/人事評価結果.csv", delim = ",", locale = locale(encoding = "Shift-JIS"))
```

## データの確認
```{r}
dim(jhk)
colnames(jhk) 
head(jhk,3) 
```

## ヒストグラムの描画
### メモ
jhkから「ストレス」の値を取り出し、20の階級（breaks）でヒストグラムを作成。
```{r}
#パッケージlatticeの読み込み
library(lattice)
histogram(~ストレス, data=jhk,breaks=20,type="count")
```

## 値の算出
### メモ
tableで度数分布表を作成し、sortで昇順にする。
```{r}
mean(jhk$ストレス)
median(jhk$総合)
# 最頻値
sort(table(jhk$年代))
```

## 散布度の算出
### メモ
平均偏差とは、データの中央値に対するすべての偏差の絶対値を平均した値。平均値や中央値からのデータのばらつきを測るためのもの。
```{r}
# 標準偏差
sd(jhk$ストレス)
# 分散
var(jhk$総合)
# 平均偏差
mean(abs(jhk$ストレス - median(jhk$ストレス)))
```

## ヒストグラム
### メモ

```{r}
histogram(~協調性|年代+性別, data=jhk, breaks=15)
```

## 最頻値と散布図
### メモ
tapply(統計量を求める量的変数, 群、関数)
女性の方が協調性の平均が大きく散らばりが小さい。
```{r}
tapply(jhk$協調性, jhk$性別, mean)
tapply(jhk$協調性, jhk$性別, sd)
```

## 箱ひげ図
### メモ
horizontal=FALSEで縦置き
```{r}
boxplot(jhk$技能, horizonal=TRUE)
#性別毎に「協調性」の箱ヒゲ図
boxplot(協調性~性別,data=jhk, horizontal=TRUE)

#四分位数も含めた要約統計量の算出
summary(jhk$技能)
```
